require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.2'

#if target.name.start_with?('Flipper') target.build_configurations.each do |config| config.build_settings['VALID_ARCHS'] = 'arm64 arm64e armv7 armv7s x86_64' end end

target 'agilesoftReactNative' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'agilesoftReactNativeTests' do
    inherit! :complete
    # Pods for testing
  end

  use_flipper!()
  post_install do |installer|
    react_native_post_install(installer)
        installer.pods_project.build_configurations.each do |config| config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] =  "arm64"
        end
  end
end





